# Generated by Django 2.1.7 on 2019-02-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('usedByTestSuites', models.CharField(max_length=1000)),
            ],
        ),
    ]
