# Generated by Django 2.1.7 on 2019-03-15 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('name', models.CharField(default='TestName', max_length=200)),
                ('accessID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.FileField(upload_to='eos/scripts/')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('usedByTestSuites', models.CharField(max_length=1000)),
                ('accessID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SuiteName', max_length=200)),
                ('accessID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('TestList', models.TextField(null=True)),
            ],
        ),
    ]
