# Generated by Django 2.1.7 on 2019-02-19 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='accessID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='script',
            field=models.FileField(upload_to='scripts/'),
        ),
    ]
