# Generated by Django 2.1.7 on 2019-03-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0002_auto_20190219_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestList', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='script',
            field=models.FileField(upload_to='eos/scripts/'),
        ),
    ]
