# Generated by Django 2.1.7 on 2019-03-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0003_auto_20190304_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='name',
            field=models.CharField(default='SuiteName', max_length=200),
        ),
    ]
