# Generated by Django 2.1.7 on 2019-03-05 00:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0004_testsuite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='accessID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
