# Generated by Django 2.1.7 on 2019-03-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='ReportName', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
