# Generated by Django 2.1.7 on 2019-03-14 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0007_auto_20190314_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.AddField(
            model_name='report',
            name='accessID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
