# Generated by Django 2.1.7 on 2019-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eos', '0008_auto_20190314_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='TestName', max_length=200),
        ),
    ]
